# Runner server requires following for build!
# dotnet-sdk-3.1
# dotnet-sdk-2.2

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - 'dotnet clean'
    - 'dotnet build -c Release'

deploy_staging:
  stage: deploy
  script:
  - eval "$(ssh-agent -s)"
  - ssh-add <(echo "$PKgitlab")
  - ssh ubuntu@"$URLdevops" './DE-DeployPrep.sh'
  - 'dotnet publish -c Release'
  - rsync -azhe ssh /home/gitlab-runner/builds/MsHgSUxs/0/tcdev/de2020master/TechCertain.WebUI/bin/Release/netcoreapp3.1/ ubuntu@$URLdevops:/home/ubuntu/projects/dealengine
  - ssh ubuntu@"$URLdevops" './DE-DeployFin.sh'

  environment:
    name: staging
    url: https://devops.techcertain.com
  when: manual
  dependencies:
    - build
    
deploy_demo:
  stage: deploy
  script:
  - eval "$(ssh-agent -s)"
  - ssh-add <(echo "$PKgitlab")
  - ssh -o StrictHostKeyChecking=no ubuntu@"$URLdemo" './DE-DeployPrep.sh'
  - 'dotnet publish -c Release'
  - rsync -azhe ssh /home/gitlab-runner/builds/MsHgSUxs/0/tcdev/de2020master/TechCertain.WebUI/bin/Release/netcoreapp3.1/ ubuntu@$URLdemo:/home/ubuntu/projects/dealengine
  - ssh ubuntu@"$URLdemo" './DE-DeployFin.sh'

  environment:
    name: demo
    url: https://demo.proposalonline.com
  when: manual
  dependencies:
    - build

# useful for first time connection (- ssh -o StrictHostKeyChecking=no ubuntu@"$URLmpak" 'command')

deploy_marsh:
  stage: deploy
  script:
  - eval "$(ssh-agent -s)"
  - ssh-add <(echo "$PKgitlab")
  - ssh ubuntu@"$URLmarsh" './DE-DeployPrep.sh'
  - 'dotnet publish -c Release'
  - rsync -azhe ssh /home/gitlab-runner/builds/MsHgSUxs/0/tcdev/de2020master/TechCertain.WebUI/bin/Release/netcoreapp3.1/ ubuntu@$URLdevops:/home/ubuntu/projects/dealengine
  - ssh ubuntu@"$URLmarsh" './DE-DeployFin.sh'

  environment:
    name: marsh
    url: https://staging.mnzconnect.com
  when: manual
  dependencies:
    - build

deploy_insw:
  stage: deploy
  script:
  - eval "$(ssh-agent -s)"
  - ssh-add <(echo "$PKgitlab")
  - ssh ubuntu@"$URLinsw" './DE-DeployPrep.sh'
  - 'dotnet publish -c Release'
  - rsync -azhe ssh /home/gitlab-runner/builds/MsHgSUxs/0/tcdev/de2020master/TechCertain.WebUI/bin/Release/netcoreapp3.1/ ubuntu@$URLdevops:/home/ubuntu/projects/dealengine
  - ssh ubuntu@"$URLinsw" './DE-DeployFin.sh'

  environment:
    name: insw
    url: https://dealengine.tai.co.nz
  when: manual
  dependencies:
    - build
