stages:
#  - build
  - deploy

before_script:  

# Runner server requires following for build
# dotnet-sdk-3.1
# dotnet-sdk-2.2

#build:
#  stage: build
#  script:
#    - echo "Cleaning previous build..."
#    - 'dotnet clean'
#    - echo "Building project..."
#    - 'dotnet build -c Release'

before_script:

deploy_staging:
  stage: deploy
  script:
  - echo "Compiling code..."
#  - 'dotnet publish -c Release'
  - ls -la
  - ls -la ~/.ssh/
  - eval "$(ssh-agent -s)"
  - ssh-add <(echo "$PKgitlab")
  - ssh -o StrictHostKeyChecking=no ubuntu@"$URLdevops" 'rm -rf /var/www/dealengine/publish/*'
#  - scp -P22 -r . ubuntu@"$URLdevops":/var/www/dealengine
#  - rsync -azhe ssh /path/to/project ubuntu@$URLdevops:/home/ubuntu/
#  Restart dealengine service
#  - echo "Restarting DealEngine Service...

  environment:
    name: staging
    url: https://devops.techcertain.com
  when: manual
#  dependencies:
#    - build

deploy_marsh:
  stage: deploy
  script:
  - echo "Compiling code..."
  - 'dotnet publish -c Release --self-contained -r ubuntu.18.04-x64'

#  - echo "Establishing Connection to devops.techcertain.com..."
#  - ssh-add <(echo "$PRIVATE_KEY")
#  - ssh -o StrictHostKeyChecking=no user@"$QA_SERVER" 'rm -rf /var/www/html/*'
#  - scp -P22 -r . ubuntu@"$QA_SERVER":/var/www/dealengine
#  - rsync -azhe ssh /path/to/project ubuntu@devops.techcertain.com:/home/ubuntu/
#  Restart dealengine service
#  - echo "Restarting DealEngine Service...

  environment:
    name: marsh
    url: https://staging.mnzconnect.com
  when: manual
#  dependencies:
#    - build

deploy_insw:
  stage: deploy
  script:
  - echo "Compiling code..."
  - 'dotnet publish -c Release --self-contained -r ubuntu.18.04-x64'

#  - echo "Establishing Connection to dealengine.tai.co.nz..."
#  - ssh-add <(echo "$PRIVATE_KEY")
#  - ssh -o StrictHostKeyChecking=no user@"$QA_SERVER" 'rm -rf /var/www/html/*'
#  - scp -P22 -r . ubuntu@"$QA_SERVER":/var/www/dealengine
#  - rsync -azhe ssh /path/to/project ubuntu@devops.techcertain.com:/home/ubuntu/
#  Restart dealengine service
#  - echo "Restarting DealEngine Service...

  environment:
    name: insw
    url: https://dealengine.tai.co.nz
  when: manual
  dependencies:
#    - build
