name: CICD Pipeline

on:
  push:
    branches:
      - main
      - Rotary2024
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Clean Project
      run: dotnet clean

    #- name: Disable NuGet Source
     # run: dotnet nuget disable source IAG

    - name: Build Project
      run: dotnet build -c Release

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Run Unit Tests
      run: dotnet test --no-build --verbosity normal

  deploy_insurerotaryoceania:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'workflow_dispatch' }} # Manual Trigger

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Replace URLs in ckeditor.js
      run: |
        sed -i "s|https://localhost:44323/Image/CKGetAllImages|https://${{ secrets.URL_INSUREROTARYOCEANIA }}/Image/CKGetAllImages|g" DealEngine.WebUI/wwwroot/ckeditor/ckeditor5-techcertain/build/ckeditor.js
        sed -i "s|https://localhost:44323/Image/_|https://${{ secrets.URL_INSUREROTARYOCEANIA }}/Image/_|g" DealEngine.WebUI/wwwroot/ckeditor/ckeditor5-techcertain/build/ckeditor.js
        sed -i "s|https://localhost:44323/Image/CKUpload|https://${{ secrets.URL_INSUREROTARYOCEANIA }}/Image/CKUpload|g" DealEngine.WebUI/wwwroot/ckeditor/ckeditor5-techcertain/build/ckeditor.js
        sed -i "s|https://localhost:44323/Image/|https://${{ secrets.URL_INSUREROTARYOCEANIA }}/Image/|g" DealEngine.WebUI/wwwroot/ckeditor/ckeditor5-techcertain/build/ckeditor.js

    - name: Execute Deploy Preparation Script
      run: ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.URL_INSUREROTARYOCEANIA }} './DE-DeployPrep.sh'

    - name: Copy Login Text File
      run: cp ~/general/_LoginText.cshtml DealEngine.WebUI/Views/Account/_LoginText.cshtml

    - name: Publish Project
      run: dotnet publish -c Release

    - name: Deploy Files via rsync
      run: |
        rsync -azhe ssh DealEngine.WebUI/bin/Release/net6.0/ ubuntu@${{ secrets.URL_INSUREROTARYOCEANIA }}:/home/ubuntu/projects/dealengine

    - name: Execute Final Deploy Script
      run: ssh ubuntu@${{ secrets.URL_INSUREROTARYOCEANIA }} './DE-DeployFin.sh'
