name: CICD Pipeline

on:
  push:
    branches:
      - Rotary2024  # Change as needed
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    name: Build .NET 6
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Clean and Restore Dependencies
        run: |
          dotnet nuget locals all --clear
          dotnet clean
          dotnet restore

      - name: Disable NuGet Source if Exists
        run: |
          if dotnet nuget list source | grep -q "IAG"; then
            dotnet nuget disable source IAG
          else
            echo "NuGet source 'IAG' not found. Skipping."
          fi

      - name: Build Project
        run: dotnet build -c Release --no-restore

  deploy_insurerotaryoceania:
    name: Deploy to Rotary Oceania
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.URLINSUREROTARYOCEANIA }} >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Replace URLs in CKEditor
        run: |
          sed -i
